// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFileConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFileConfig'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadFileConfig(arg1) {
  return window['go']['main']['App']['LoadFileConfig'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
