// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFileConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetPathFile(arg1:main.ReplaceFileConfigParam):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadFileConfig(arg1:string):Promise<main.LoadFileConfigResponse>;

export function ReplaceFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectFolder():Promise<string>;
