// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFileConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function LoadFileConfig(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;
