name: Build Wails App

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64, 386]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Instalar Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Instalar PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9 # ou a versão que você usa

      - name: Instalar dependências do frontend
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "${{ matrix.arch }}"
          wails build -o "build/MeuApp-${{ matrix.arch }}.exe"
        shell: pwsh

      - name: Publicar no Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
